#!/bin/sh
# NVMC user login shell
vm=""
cmd="ncvnc"

readargs() {
	if test "$1" = "ncvnc"; then
		cmd="ncuser vncs $2 $HOME/$vm.vnc"
		vm="$2"
		return 0
	fi
	if test "$1" = "ncssh"; then
		cmd="ncuser sshs $2 $HOME/$vm.vnc"
		vm="$2"
		return 0
	fi
	if test "$1" = "ncuser"; then
		cmd="ncuser $2 $3"
		vm="$3"
		return 0
	fi
	if test "$1" = "passwd"; then
		passwd
		exit
	fi
	vm="$1"
}

readargs $2

if test -z "$vm"; then
	echo "VM name not specified."
	exit 1
fi

if /var/nc/$cmd $HOME/$vm.vnc; then
	echo "Forwarding connections to VM $vm."
	read ln
else
	echo "Failed to set up connection forwarding."
	exit 1
fi
