#!/bin/sh
# NVMC's helper commands

# Default directories
NCDIR="/var/nc"
VMDIR="$NCDIR/vms"
HSDIR="$NCDIR/hosts"
IMDIR="$NCDIR/imgs"
IMDIR_MAIN="$NCDIR/imgs_main"
MACPT="52:54:CC:5E:%02X:%02X"
ADDPT="10.1.%d.%d"

# mkvm variables
mems="1"
cpus="1"
initdisk="10"
disk=""
user="root"
name=""
host="host1"
temp=""
gpu=""
iso=""
img=""
net=""
cln=""

mkvmusage() {
	echo "Usage: mkvm options"
	echo
	echo "Options:"
	echo "  -n name    VM name"
	echo "  -u user    VM owner"
	echo "  -c cpus    CPU count"
	echo "  -m mem     memory size (GB)"
	echo "  -d size    disk size (GB)"
	echo "  -h host    VM host"
	echo "  -t temp    template (use -T to list)"
	echo "  -q img     disk image (qcow2)"
	echo "  -i iso     CD/DVD ISO"
	echo "  -g gpu#    GPU number to passthrough (1, 2)"
	echo "  -net x     NIC type (b: bridge, u: slirp)"
	echo "  -cln x     disk image clone type (c: copy, o: overlay)"
}

mkvmoptions() {
	while test "$#" -ge 1; do
		case "$1" in
			-c)
				cpus="$2"
				shift && test "$#" -ge 1 && shift
				;;
			-m)
				mems="$2"
				shift && test "$#" -ge 1 && shift
				;;
			-d)
				disk="$2"
				shift && test "$#" -ge 1 && shift
				;;
			-D)
				initdisk="$2"
				shift && test "$#" -ge 1 && shift
				;;
			-n)
				name="$2"
				shift && test "$#" -ge 1 && shift
				;;
			-u)
				user="$2"
				shift && test "$#" -ge 1 && shift
				;;
			-h)
				host="$2"
				shift && test "$#" -ge 1 && shift
				;;
			-t)
				temp="$2"
				shift && test "$#" -ge 1 && shift
				;;
			-q)
				img="$2"
				shift && test "$#" -ge 1 && shift
				;;
			-i)
				iso="$iso $2"
				shift && test "$#" -ge 1 && shift
				;;
			-g)
				gpu="$gpu $2"
				shift && test "$#" -ge 1 && shift
				;;
			-net)
				net="$2"
				shift && test "$#" -ge 1 && shift
				;;
			-cln)
				cln="$2"
				shift && test "$#" -ge 1 && shift
				;;
			-T)
				test -f $NCDIR/TEMP && cat $NCDIR/TEMP
				return 1
				;;
			*)
				mkvmusage
				return 1
				;;
		esac
	done
}

xmkvm() {
	shift
	if test "$#" = "0"; then
		mkvmusage
		return 1
	fi
	if ! mkvmoptions $*; then
		return 2
	fi
	# Read template options
	if test -n "$temp" && grep "^$temp	" $NCDIR/TEMP 1>/dev/null 2>&1; then
		opts="`grep \"^$temp	\" $NCDIR/TEMP | cut -f 2`"
		mkvmoptions $opts
	fi
	# Check VM name
	if test -z "$name"; then
		echo "VM name cannot be empty"
		return 3
	fi
	vm="$VMDIR/$name"
	if test ! -d "$HSDIR/$host"; then
		echo "Unknown host <$host>"
		return 4
	fi
	if ! id $user >/dev/null 2>&1; then
		echo "Unknown user <$user>"
		return 5
	fi
	mkdir -p $VMDIR
	if ! mkdir $vm; then
		echo "Directory <$vm> already exists"
		return 6
	fi
	# Create VM files
	echo $cpus >$vm/CPUS
	echo $mems >$vm/MEMS
	echo $initdisk >$vm/DISK
	echo $gpu | wc -w >$vm/GPUS
	echo $host >$vm/HOST
	id -u $user >$vm/USER
	# Adding Qemu options
	for x in $iso; do
		echo "-drive file=$IMDIR/$x,format=raw,readonly=on,media=cdrom" >>$vm/OPTS
	done
	for x in $gpu; do
		test "$x" = "1" && echo "-device vfio-pci,host=0b:00.1 -device vfio-pci,host=0b:00.2 -device vfio-pci,host=0b:00.0 -device vfio-pci,host=0b:00.3" >>$vm/OPTS
		test "$x" = "2" && echo "-device vfio-pci,host=84:00.1 -device vfio-pci,host=84:00.2 -device vfio-pci,host=84:00.0 -device vfio-pci,host=84:00.3" >>$vm/OPTS
	done
	# Create INIT script
	echo "#!/bin/sh" >$vm/INIT
	echo "test -f disk && exit" >>$vm/INIT
	# Create a local copy of referenced images if they do not exist
	for x in $img $iso; do
		echo "if test ! -f $IMDIR/$x && test -f $IMDIR_MAIN/$x; then" >>$vm/INIT
		echo "	mkdir -p $IMDIR/" >>$vm/INIT
		echo "	cp $IMDIR_MAIN/$x $IMDIR/$x" >>$vm/INIT
		echo "fi" >>$vm/INIT
	done
	# Create VM's disk image
	if test -z "$cln" -o "$cln" = "c"; then
		echo "cp $IMDIR/$img disk" >>$vm/INIT
	else
		echo "qemu-img create -f qcow2 -b $IMDIR/$img disk" >>$vm/INIT
	fi
	chmod +x $vm/INIT
	if test -n "$disk"; then
		if test "$disk" -gt "`cat $vm/DISK`"; then
			echo "#!/bin/sh" >$vm/ONCE
			echo "qemu-img resize disk ${disk}G" >>$vm/ONCE
			chmod +x $vm/ONCE
			echo $disk >$vm/DISK
		fi
	fi
	# Allocate a VM slot
	$NCDIR/nc slot $name
	slot="`cat $vm/SLOT`"
	# VM information
	echo "VM name         $name"
	echo "VM memory size  $mems"
	echo "VM cpu count    $cpus"
	echo "VM owner        $user"
	echo "VM host         $host"
	echo "VM slot         $slot"
	# Assign a MAC address (for bridged networking)
	if test -z "$net" -o "$net" = "b"; then
		printf "$MACPT\\n" "`expr $slot / 256`" "`expr $slot % 256`" >$vm/EMAC
		emac="`cat $vm/EMAC`"
		echo "VM mac address  $emac"
	fi
}

xrmvm() {
	shift
	$NCDIR/nc quit $1
	$NCDIR/nc drop $1
}

xpush() {
	shift
	$NCDIR/nc push $1
}

xmkuser() {
	shift
	if test "$#" -lt 2; then
		echo "Usage: $0 username password"
		return 1
	fi
	user="$1"
	pass="$2"
	group="users"
	name=""
	if test -d /home/$user; then
		echo "User $user already exists"
		return 2
	fi
	if ! useradd -d /home/$user -g $group -m -N -c "$name" -s /var/nc/nclogin $user; then
		echo "Failed to create user $name"
		return 3
	fi
	chmod 700 /home/$user
	if ! echo $user:$pass | chpasswd; then
		echo "Failed to create user $name's password"
		return 4
	fi
}

xrmuser() {
	shift
	user="$1"
	if test -z "$user"; then
		echo "Usage: $0 username"
		return 1
	fi
	if test ! -d /home/$user; then
		echo "User $user does not exist"
		return 1
	fi
	if ! userdel $user; then
		echo "Failed to remove user $user"
		return 1;
	fi
	rm -r /home/$user
}

xbackup() {
	name="nvmc`date '+%Y%m%d%H%M%S'`"
	cp -r /var/nc $name
	tar czf $name.tar.gz $name
	rm -r "$name"
}

xmacs() {
	shift
	n="$1"
	test -z "$n" && n="200"
	for i in `seq 0 $n`; do
		printf "$MACPT " "`expr $i / 256`" "`expr $i % 256`"
		printf "$ADDPT\n" "`expr 2 + $i / 250`" "`expr $i % 250 + 1`"
	done
}

xaddr() {
	shift
	vm="$1"
	if test -z "$vm"; then
		echo "Usage: $0 vm_name"
		return 1
	fi
	if test ! -d "$VMDIR/$vm"; then
		echo "Directory $VMDIR/$vm does not exist"
		return 2
	fi
	slot="`cat $VMDIR/$vm/SLOT`"
	printf "$ADDPT\n" "`expr 2 + $slot / 250`" "`expr $slot % 250 + 1`"
}

xstop() {
	shift
	vm="$1"
	$NCDIR/nc user "$vm" -
	$NCDIR/nc quit "$vm"
}

xcont() {
	shift
	vm="$1"
	$NCDIR/nc user "$vm" +
}

xhost() {
	shift
	$NCDIR/nc host "$@"
}

editusage() {
	echo "Usage: edit options"
	echo
	echo "Options:"
	echo "  -n name    VM name"
	echo "  -c cpus    CPU count"
	echo "  -m mem     memory size (GB)"
	echo "  -d disk    disk size (GB)"
}

xedit() {
	shift
	if test "$#" = "0"; then
		editusage
		return 1
	fi
	cpus=""
	mems=""
	disk=""
	name=""
	while test "$#" -ge 1; do
		case "$1" in
			-n)
				name="$2"
				shift && test "$#" -ge 1 && shift
				;;
			-c)
				cpus="$2"
				shift && test "$#" -ge 1 && shift
				;;
			-m)
				mems="$2"
				shift && test "$#" -ge 1 && shift
				;;
			-d)
				disk="$2"
				shift && test "$#" -ge 1 && shift
				;;
			*)
				editoptions
				return 1
				;;
		esac
	done
	# Check VM name
	if test -z "$name"; then
		echo "VM name cannot be empty"
		return 2
	fi
	vm="$VMDIR/$name"
	if test ! -d "$vm"; then
		echo "Directory $VMDIR/$vm does not exist"
		return 3
	fi
	test -n "$cpus" && echo "$cpus" >$vm/CPUS
	test -n "$mems" && echo "$mems" >$vm/MEMS
	test -n "$disk" && $NCDIR/nc size "$name" "$disk"
}

xdhcpconf() {
	shift
	echo "# VM subnet"
	echo "subnet 10.1.0.0 netmask 255.255.0.0 {"
	echo "  range 10.1.2.1 10.1.254.254;"
	echo "}"
	echo "# VM IP addresses"
	i="0"
	xmacs xmacs $1 | while read x; do
		mac="`echo $x | cut -d ' ' -f 1`"
		ip="`echo $x | cut -d ' ' -f 2`"
		echo "host nvmc$i {"
		echo "  hardware ethernet $mac;"
		echo "  fixed-address $ip;"
		echo "}"
		i="`expr $n + 1`"
	done
}

# Main commands
case "$1" in
	mkuser)
		xmkuser "$@" || exit $?
		;;
	rmuser)
		xrmuser "$@" || exit $?
		;;
	mkvm)
		xmkvm "$@" || exit $?
		;;
	rmvm)
		xrmvm "$@" || exit $?
		;;
	push)
		xpush "$@" || exit $?
		;;
	addr)
		xaddr "$@" || exit $?
		;;
	stop)
		xstop "$@" || exit $?
		;;
	cont)
		xcont "$@" || exit $?
		;;
	host)
		xhost "$@" || exit $?
		;;
	edit)
		xedit "$@" || exit $?
		;;
	backup)
		xbackup "$@" || exit $?
		;;
	macs)
		xmacs "$@" || exit $?
		;;
	vmexec)
		$NCDIR/nc exec $2 || exit $?
		;;
	vmpoff)
		$NCDIR/nc poff $2 || exit $?
		;;
	vmquit)
		$NCDIR/nc quit $2 || exit $?
		;;
	vmreboot)
		$NCDIR/nc reboot $2 || exit $?
		;;
	dhcpconf)
		xdhcpconf "$@" || exit $?
		;;
	*)
		echo "Usage: $0 command [options]"
		echo
		echo "Available commands:"
		echo "  mkvm      create a VM"
		echo "  rmvm      remove a VM"
		echo "  push      copy a VM to a host"
		echo "  addr      print VM IP address"
		echo "  stop      stop a VM and disable access"
		echo "  cont      enable VM access"
		echo "  edit      edit VM configuration"
		echo "  host      show hosts"
		echo "  mkuser    create a user"
		echo "  rmuser    remove a user"
		echo "  backup    create a backup of /var/nc"
		echo "  macs      print MAC-IP address mappings"
		echo "  dhcpconf  generate dhcpd config"
		;;
esac
